name: BUILD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Yarn
        run: npm i yarn -g
      - name: Build
        run: yarn && yarn build
      - name: Run unit tests
        run: yarn test
      - name: Install Newman
        run: npm i newman -g
      - name: Start service
        run: yarn start &
      - name: Run API tests
        run: |
          newman run ./assets/postman/newman.postman_collection.json \
            --env-var host=http://127.0.0.1:3000
